version: '2'
services:
  database:
    build:
      context: .
      dockerfile: docker/Dockerfile-postgres
  confluence:
    build:
      context: .
      dockerfile: docker/Dockerfile-confluence
    ports:
      - '8090:8090'
    links:
      - database
    depends_on:
      - database
