FROM mysql:5.7

ENV MYSQL_DATABASE="confluence"
ENV MYSQL_ROOT_PASSWORD="S({hp!?QUth4~V4J"
ENV MYSQL_DATABASE="confluence"
ENV MYSQL_USER="confluence"
ENV MYSQL_PASSWORD="g[fv7H[KVt<7,h[f"
ENV MYSQL_CHARSET="utf8_bin"

RUN echo 'sql-mode="NO_AUTO_VALUE_ON_ZERO"' >> /etc/alternatives/my.cnf
RUN echo 'character-set-server="utf8"' >> /etc/alternatives/my.cnf
RUN echo 'collation-server="utf8_bin"' >> /etc/alternatives/my.cnf
RUN echo 'default-storage-engine="INNODB"' >> /etc/alternatives/my.cnf
RUN echo 'max_allowed_packet="256M"' >> /etc/alternatives/my.cnf
RUN echo 'innodb_log_file_size="2GB"' >> /etc/alternatives/my.cnf
RUN echo 'transaction-isolation="READ-COMMITTED"' >> /etc/alternatives/my.cnf
RUN echo 'binlog_format="row"' >> /etc/alternatives/my.cnf
