FROM mysql:5.7

ENV MYSQL_DATABASE="confluence"
ENV MYSQL_ROOT_PASSWORD="S({hp!?QUth4~V4J"
ENV MYSQL_DATABASE="confluence"
ENV MYSQL_USER="confluence"
ENV MYSQL_PASSWORD="g[fv7H[KVt<7,h[f"

#ADD /config/docker.cnf /etc/mysql/conf.d/
